# Generated by CloudEdging Operator Agent — DRAFT, review before applying.
# Target provider: Hetzner Cloud
# This is a generated migration draft. Verify every value against your
# actual requirements before running terraform apply.
#
# Includes: SSH key reference, private network + subnet, basic firewall.
# Does NOT include: software install, data migration, app configuration.
# Those are intentionally out of scope — a human completes them.

terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.45"
    }
  }
}

variable "hcloud_token" {
  description = "Hetzner Cloud API token"
  type        = string
  sensitive   = true
}

variable "ssh_key_name" {
  description = "Name of an existing SSH key in your Hetzner project (Security > SSH Keys)"
  type        = string
}

variable "admin_ssh_cidr" {
  description = "CIDR allowed to SSH to servers (your IP/range). Default is open — TIGHTEN THIS."
  type        = string
  default     = "0.0.0.0/0"  # INSECURE DEFAULT — restrict to your IP before applying
}

provider "hcloud" {
  token = var.hcloud_token
}

# --- private network ---
# Servers attach to this so they reach each other over private IPs
# rather than the public internet.
resource "hcloud_network" "main" {
  name     = "cloudedging-migration-net"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "main" {
  network_id   = hcloud_network.main.id
  type         = "cloud"
  network_zone = "eu-central"  # match your server location region
  ip_range     = "10.0.1.0/24"
}

# --- firewall ---
# Conservative baseline: SSH from your admin CIDR, free traffic on the
# private network between migrated servers, everything else inbound blocked.
# Tighten per-service ports based on your actual dependency graph:
#   api-server -> primary-postgres: open the relevant service port (e.g. 5432 postgres, 6379 redis) on the private network
#   api-server -> redis-cache: open the relevant service port (e.g. 5432 postgres, 6379 redis) on the private network
resource "hcloud_firewall" "main" {
  name = "cloudedging-migration-fw"

  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = [var.admin_ssh_cidr]
  }

  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "any"
    source_ips = ["10.0.0.0/16"]  # private network — inter-server traffic
  }

  rule {
    direction  = "in"
    protocol   = "icmp"
    source_ips = [var.admin_ssh_cidr]
  }
}

# --- database: primary-postgres (postgres 15) ---
# Source spec: engine=postgres, version=15, size_gb=50, was_managed=True
# IMPORTANT: Hetzner has no managed DB equivalent. This generates a
# SELF-MANAGED database server + data volume. You must install postgres 15, configure it, and migrate
# data separately. Managed->self-managed DB migration is high-risk and
# should follow the Operator DB runbook with DBA oversight — NOT automated.
resource "hcloud_server" "primary_postgres" {
  name         = "primary-postgres"
  server_type  = "cx42"  # SUGGESTION — verify for DB workload
  image        = "ubuntu-22.04"
  location     = "nbg1"
  ssh_keys     = [var.ssh_key_name]
  firewall_ids = [hcloud_firewall.main.id]
  network {
    network_id = hcloud_network.main.id
  }
  depends_on = [hcloud_network_subnet.main]
  labels = {
    managed_by = "cloudedging"
    role       = "database"
    engine     = "postgres"
  }
}

resource "hcloud_volume" "primary_postgres_data" {
  name      = "primary-postgres-data"
  size      = 50  # GB — sized from source size_gb=50, verify
  server_id = hcloud_server.primary_postgres.id
  automount = true
  format    = "ext4"
}

# --- database: redis-cache (redis 7) ---
# Source spec: engine=redis, version=7, size_gb=4, was_managed=True
# IMPORTANT: Hetzner has no managed DB equivalent. This generates a
# SELF-MANAGED database server + data volume. You must install redis 7, configure it, and migrate
# data separately. Managed->self-managed DB migration is high-risk and
# should follow the Operator DB runbook with DBA oversight — NOT automated.
resource "hcloud_server" "redis_cache" {
  name         = "redis-cache"
  server_type  = "cx32"  # SUGGESTION — verify for DB workload
  image        = "ubuntu-22.04"
  location     = "nbg1"
  ssh_keys     = [var.ssh_key_name]
  firewall_ids = [hcloud_firewall.main.id]
  network {
    network_id = hcloud_network.main.id
  }
  depends_on = [hcloud_network_subnet.main]
  labels = {
    managed_by = "cloudedging"
    role       = "database"
    engine     = "redis"
  }
}

resource "hcloud_volume" "redis_cache_data" {
  name      = "redis-cache-data"
  size      = 10  # GB — sized from source size_gb=4, verify
  server_id = hcloud_server.redis_cache.id
  automount = true
  format    = "ext4"
}

# --- compute: api-server ---
# Source spec: vcpu=2, ram_gb=4, os=ubuntu-22.04, runtime=node-20, count=2
# Suggested Hetzner server_type below is a starting point — VERIFY against
# your CPU/RAM/perf needs (Hetzner CX = shared vCPU; consider CCX dedicated for prod).
resource "hcloud_server" "api_server" {
  count        = 2
  name         = "api-server-${count.index}"
  server_type  = "cx22"  # SUGGESTION — verify
  image        = "ubuntu-22.04"
  location     = "nbg1"  # Nuremberg — change to fsn1/hel1/ash/hil as needed
  ssh_keys     = [var.ssh_key_name]
  firewall_ids = [hcloud_firewall.main.id]
  network {
    network_id = hcloud_network.main.id
  }
  depends_on = [hcloud_network_subnet.main]
  labels = {
    managed_by = "cloudedging"
    source     = "aws"
  }
}

